-- Secure, one-time account invitation for ECP/PDP partners created by an administrator.
-- The set-password link is generated by Supabase Auth and is deliberately not stored in email_logs.

INSERT INTO public.email_templates (
  template_key,
  name,
  category,
  subject,
  html_body,
  text_body,
  variables,
  is_active
)
VALUES (
  'partner_account_invitation',
  'Partner Account Invitation',
  'partner',
  'Set up your BDA Partner account',
  $html$
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body style="margin:0;padding:0;background:#f0f6ff;font-family:Arial,Helvetica,sans-serif;color:#0d1f4e;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;background:#f0f6ff;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#ffffff;border:1px solid #dbeafe;border-radius:16px;overflow:hidden;">
            <tr>
              <td style="padding:34px 36px;background:linear-gradient(135deg,#0f91e0 0%,#1c4a8b 56%,#0d1f4e 100%);">
                <p style="margin:0 0 10px;color:#ffffff;font-size:13px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;">Business Development Association</p>
                <h1 style="margin:0;color:#ffffff;font-size:29px;line-height:1.2;">Welcome to BDA Partner Portal</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:36px;">
                <p style="margin:0 0 20px;font-size:16px;line-height:1.65;">Dear {{first_name}},</p>
                <p style="margin:0 0 20px;font-size:16px;line-height:1.65;color:#334155;">
                  A BDA Partner Portal account has been created for <strong>{{organisation_name}}</strong> as a {{partner_type_full}}.
                </p>
                <p style="margin:0 0 24px;font-size:16px;line-height:1.65;color:#334155;">
                  To protect the account, please choose your own password through the secure button below. No temporary password has been issued or shared.
                </p>
                <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 auto 24px;">
                  <tr>
                    <td align="center" style="border-radius:8px;background:#0f91e0;">
                      <a href="{{set_password_url}}" style="display:inline-block;padding:15px 26px;color:#ffffff;font-size:16px;font-weight:700;line-height:1;text-decoration:none;">Set Your Password</a>
                    </td>
                  </tr>
                </table>
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;background:#f0f6ff;border-radius:10px;">
                  <tr>
                    <td style="padding:18px 20px;">
                      <p style="margin:0 0 6px;color:#64748b;font-size:12px;font-weight:700;letter-spacing:.8px;text-transform:uppercase;">Account email</p>
                      <p style="margin:0;color:#0d1f4e;font-size:15px;font-weight:700;">{{email}}</p>
                    </td>
                  </tr>
                </table>
                <p style="margin:0 0 16px;font-size:14px;line-height:1.65;color:#475569;">
                  This secure link is for you only and may be used once. After setting your password, sign in and complete the required partner profile details before accessing the Partner Workspace.
                </p>
                <p style="margin:0;font-size:14px;line-height:1.65;color:#475569;">
                  If you were not expecting this invitation, please contact BDA before taking any action.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:24px 36px;background:#0d1f4e;">
                <p style="margin:0;color:#dbeafe;font-size:13px;line-height:1.5;">Business Development Association (BDA)</p>
                <p style="margin:6px 0 0;color:#93c5fd;font-size:12px;line-height:1.5;">This is an automated account-security message.</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
$html$,
  'Dear {{first_name}},

A BDA Partner Portal account has been created for {{organisation_name}} as a {{partner_type_full}}.

Set your password securely using this one-time link:
{{set_password_url}}

Account email: {{email}}

After setting your password, sign in and complete the required partner profile details before accessing the Partner Workspace.

Business Development Association (BDA)',
  '["first_name", "organisation_name", "partner_type_full", "email", "set_password_url"]'::jsonb,
  true
)
ON CONFLICT (template_key) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  subject = EXCLUDED.subject,
  html_body = EXCLUDED.html_body,
  text_body = EXCLUDED.text_body,
  variables = EXCLUDED.variables,
  is_active = EXCLUDED.is_active,
  updated_at = now();
